apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo
  namespace: backend
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    name: mongo
  type: NodePort

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: backend
  labels:
    app: mongo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:3.7
        ports:
          - containerPort: 27017
            name: mongo
        volumeMounts:
          - name:  mongo
            mountPath: /data/db
      volumes:
        - name: mongo
          hostPath:
            path: /Users/jonathanburris/k8s/mongo